# Generated by Django 4.2.20 on 2025-05-27 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_item_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="list",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="lists.list"
            ),
        ),
    ]
